"""autogenerated to allow downgrade to nothing as a bugfix

Revision ID: 7122c8715ff9
Revises: 29a8d663c7ce
Create Date: 2025-06-17 22:05:14.803669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7122c8715ff9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    pass


def downgrade() -> None:
    """Downgrade schema."""
    pass
