"""empty message

Revision ID: c7c2d5b8f71c
Revises: fc9d1a0dc94e
Create Date: 2025-06-12 09:21:17.960836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7c2d5b8f71c'
down_revision: Union[str, None] = 'fc9d1a0dc94e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('freak_comment', sa.Column('removed_at', sa.DateTime(), nullable=True))
    op.add_column('freak_comment', sa.Column('removed_by_id', sa.BigInteger(), nullable=True))
    op.add_column('freak_comment', sa.Column('removed_reason', sa.SmallInteger(), nullable=True))
    op.create_foreign_key('user_banner_id', 'freak_comment', 'freak_user', ['removed_by_id'], ['id'])
    op.add_column('freak_post', sa.Column('removed_at', sa.DateTime(), nullable=True))
    op.add_column('freak_post', sa.Column('removed_by_id', sa.BigInteger(), nullable=True))
    op.add_column('freak_post', sa.Column('removed_reason', sa.SmallInteger(), nullable=True))
    op.create_foreign_key('user_banner_id', 'freak_post', 'freak_user', ['removed_by_id'], ['id'])
    op.add_column('freak_user', sa.Column('banned_reason', sa.SmallInteger(), server_default=sa.text('0'), nullable=True))
    op.alter_column('freak_user', 'ban_reason', new_column_name='banned_message')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('freak_user', 'banned_message', new_column_name='ban_reason')
    op.drop_column('freak_user', 'banned_reason')
    op.drop_constraint('user_banner_id', 'freak_post', type_='foreignkey')
    op.drop_column('freak_post', 'removed_reason')
    op.drop_column('freak_post', 'removed_by_id')
    op.drop_column('freak_post', 'removed_at')
    op.drop_constraint('user_banner_id', 'freak_comment', type_='foreignkey')
    op.drop_column('freak_comment', 'removed_reason')
    op.drop_column('freak_comment', 'removed_by_id')
    op.drop_column('freak_comment', 'removed_at')
    # ### end Alembic commands ###
