"""empty message

Revision ID: fc9d1a0dc94e
Revises: 
Create Date: 2025-06-11 18:23:07.871471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc9d1a0dc94e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('freak_comment', 'author_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_index('idx_16573_comment_parent_comment_id', table_name='freak_comment')
    op.drop_index('idx_16573_comment_parent_post_id', table_name='freak_comment')
    op.drop_index('idx_16573_comment_pub_date', table_name='freak_comment')
    op.drop_index('idx_16573_comment_user_id', table_name='freak_comment')
    op.create_index(op.f('ix_freak_comment_created_at'), 'freak_comment', ['created_at'], unique=False)
    op.alter_column('freak_post', 'author_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_index('idx_16568_post_community_id', table_name='freak_post')
    op.drop_index('idx_16568_post_pub_date', table_name='freak_post')
    op.drop_index('idx_16568_post_user_id', table_name='freak_post')
    op.add_column('freak_postreport', sa.Column('created_ip', sa.String(length=64), nullable=False))
    op.alter_column('freak_postreport', 'target_type',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('freak_postreport', 'target_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('freak_postreport', 'reason_code',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('freak_topic', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_16563_community_created_on', table_name='freak_topic')
    op.drop_index('idx_16563_community_name', table_name='freak_topic')
    op.create_index(op.f('ix_freak_topic_created_at'), 'freak_topic', ['created_at'], unique=False)
    op.create_unique_constraint(None, 'freak_topic', ['name'])
    op.alter_column('freak_user', 'joined_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('freak_user', 'is_administrator',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('freak_user', 'is_disabled_by_user',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('freak_user', 'karma',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index('idx_16578_user_join_date', table_name='freak_user')
    op.drop_index('idx_16578_user_username', table_name='freak_user')
    op.create_unique_constraint(None, 'freak_user', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'freak_user', type_='unique')
    op.create_index('idx_16578_user_username', 'freak_user', ['username'], unique=True)
    op.create_index('idx_16578_user_join_date', 'freak_user', ['joined_at'], unique=False)
    op.alter_column('freak_user', 'karma',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('freak_user', 'is_disabled_by_user',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('freak_user', 'is_administrator',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('freak_user', 'joined_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'freak_topic', type_='unique')
    op.drop_index(op.f('ix_freak_topic_created_at'), table_name='freak_topic')
    op.create_index('idx_16563_community_name', 'freak_topic', ['name'], unique=True)
    op.create_index('idx_16563_community_created_on', 'freak_topic', ['created_at'], unique=False)
    op.alter_column('freak_topic', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('freak_postreport', 'reason_code',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('freak_postreport', 'target_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('freak_postreport', 'target_type',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.drop_column('freak_postreport', 'created_ip')
    op.create_index('idx_16568_post_user_id', 'freak_post', ['author_id'], unique=False)
    op.create_index('idx_16568_post_pub_date', 'freak_post', ['created_at'], unique=False)
    op.create_index('idx_16568_post_community_id', 'freak_post', ['topic_id'], unique=False)
    op.alter_column('freak_post', 'author_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_index(op.f('ix_freak_comment_created_at'), table_name='freak_comment')
    op.create_index('idx_16573_comment_user_id', 'freak_comment', ['author_id'], unique=False)
    op.create_index('idx_16573_comment_pub_date', 'freak_comment', ['created_at'], unique=False)
    op.create_index('idx_16573_comment_parent_post_id', 'freak_comment', ['parent_post_id'], unique=False)
    op.create_index('idx_16573_comment_parent_comment_id', 'freak_comment', ['parent_comment_id'], unique=False)
    op.alter_column('freak_comment', 'author_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
